### ISSUE TITLE
Hidden attribute

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/node-red-contrib-polymer#16]

**Comment by hobbyquaker** [comment]
skipping that. can be done via sending `{"style":{"display":"none"}}` to a widget

**Comment by M0ebiu5** [comment]
With this solution: can i have widgets on the page default as hidden and show them on demand?

**Comment by hobbyquaker** [comment]
They will render to whatever the last msg to them was (as long as Node-RED wasn't restarted, but you could also inject once on startup with the inject node, so this would be persistent even when Node-RED was restarted). I think I will add this as an option to every widget also, either the hidden attribute or just the possibility to add arbitrary style attributes.

**Comment by M0ebiu5** [comment]
I think there should be an option for every widget. Cause i want to show certain widgets only on demand and if i need to inject first the hidden attribute, it complicates things on node-red side, and also on browser (rendering) side.
