### ISSUE TITLE
Feature request: Page - make sidebar optional

### ISSUE THREAD

**Issue by M0ebiu5** [hobbyquaker/node-red-contrib-polymer#19]
It should be optional to show the sidebar (or menu). Now, depending on the screen size, the sidebar or menu is shown.

**Comment by hobbyquaker** [comment]
Will do this asap, will create a few more options that can be configured in a site-node

**Comment by hobbyquaker** [comment]
You can now hide the menu on screens >640px width, take a look at the options of the "Site" node. If this is satisfying for you pls close this issue

**Comment by M0ebiu5** [comment]
"Hide menu" option works, but if you activate the side menu and click on the entry of the already opened page, it wont close. Also the cursor changes into a caret, when hovering over the entry.

**Comment by hobbyquaker** [comment]
True, but you can still swipe the menu away or close it by clicking right of it, don't you? Do you see this as a bug that has to be fixed? 
Thing is that the menu closing is triggered by the page-change event - and if you click on the page you already are there is no change ;)

**Comment by M0ebiu5** [comment]
I wouldnt call it a bug rather than an "unelegancy" :)
It's a little confusing, but if it's hard to fix, we should move on...

**Comment by M0ebiu5** [comment]
Sorry, but "close menu when clicked on active item (closes #19)" is not working here (chrome).

**Comment by hobbyquaker** [comment]
i fear this is caused by touch vs click. You tested it on a touch device?

**Comment by M0ebiu5** [comment]
I tested both - with touch (Android) and click (Win)
It's super low priority - if it's difficult, dont waste too much time on it...

**Comment by M0ebiu5** [comment]
Fixed with 0.0.7
