### ISSUE TITLE
FR: external resource widget

### ISSUE THREAD

**Issue by M0ebiu5** [hobbyquaker/node-red-contrib-polymer#22]
The idea is to have a node, who handles the visualization of external resources.

Example 1: enter the url of an image (eg webcam), size, refresh interval and timeout. When the node is shown, it refreshes the image every x seconds until the timeout. A click on the widget, restarts the refresh cycle.
Example 2: feed the node html code (pre-parsed gas price, train departure times, etc). 
Example 3: enter an url and a css selector (like the html node) and the node renders the result. The advantage would be, that the node handles the refresh interval and accesses the source when needed.

I know all this could be done via the template node, but i think a node would be more convenient and consistent with the ui.

**Comment by hobbyquaker** [comment]
ack :)

**Comment by hobbyquaker** [comment]
Example 1 is implemented, except for the timeout/click thing. Will add that later. 
For 2/3 I will create a new Widget (#24), that needs some workaround to get html rendered (Polymer doesn't allow this in "normal" templates...)
