### ISSUE TITLE
Chrome Android: Site does not load, if attribute styles is not empty

### ISSUE THREAD

**Issue by M0ebiu5** [hobbyquaker/node-red-contrib-polymer#42]
If the site node has anything in it's styles attribute , chrome on Android does not load or render the site. (even if its only `<style></style>`)

Edit: just saw, that the <style> tag is not supported at all. But without the styles tag, there is no syntax highlighting in the edit box.

**Comment by M0ebiu5** [comment]
Problem was caused by an older version of chrome 50.x...Latest version works 56.x

**Comment by hobbyquaker** [comment]
In the node there should be no need for the `<style>` tag. Syntax Highlighting is still a problem, will have to think about this again...

**Comment by M0ebiu5** [comment]
Syntax highlighting is nice to have, i was surprised that the chrome version must be so high (thinking about old devices...).
