### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by hardillb** [hobbyquaker/node-red-contrib-polymer#9]
Please referrer to the Node-RED docs on [naming](http://nodered.org/docs/creating-nodes/packaging#naming) nodes, 3rd party nodes should start `node-red-contrib-` to distinguish them from nodes owned/supported by the core Node-RED team

**Comment by hobbyquaker** [comment]
thx for the hint

**Comment by hardillb** [comment]
Remember to delete/remove the version pushed to npm as well

**Comment by hobbyquaker** [comment]
done :)
